import Motor as motor
import time

motor.moveMotor2(True)
time.sleep(1)
motor.stopMotor2()
time.sleep(1)
motor.moveMotor2(False)
time.sleep(1)
motor.stopMotor2()
time.sleep(1)


motor.moveMotor1(True)
time.sleep(1.5)
motor.stopMotor1()
time.sleep(1)
motor.moveMotor2(True)
time.sleep(1)
motor.stopMotor2()
time.sleep(1)
motor.moveMotor2(False)
time.sleep(1)
motor.stopMotor2()
time.sleep(1)
motor.moveMotor1(False)
time.sleep(1.5)
motor.stopMotor1()
time.sleep(1)

motor.moveMotor1(False)
time.sleep(1.5)
motor.stopMotor1()
time.sleep(1)
motor.moveMotor2(True)
time.sleep(1)
motor.stopMotor2()
time.sleep(1)
motor.moveMotor2(False)
time.sleep(1)
motor.stopMotor2()
time.sleep(1)
motor.moveMotor1(True)
time.sleep(3)
motor.stopMotor1()
time.sleep(1)
motor.moveMotor1(False)
time.sleep(1.5)
motor.stopMotor1()
time.sleep(1)

motor.exit()